sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - python setup.py clean --all
  - python setup.py install

script: flake8 . && python setup.py test
