sudo: false
language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install "setuptools>=40.5.0,<41"
  - pip install -r requirements.txt
  - python setup.py clean --all
  - python setup.py install

script: flake8 . && python setup.py test
