name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ 2.7, 'pypy3', 3.5, 3.6, 3.7, 3.8, 3.9]
    name: Test Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: |
          pip install -r requirements.txt
          flake8 . && python setup.py test